# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Maven Package

on:
  release:
    types: [created]
  push:
    branches:
      - master  # 当推送到 master 分支时触发
  pull_request:
    branches:
      - master  # 当有针对 master 分支的 pull request 时触发

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17 for x64
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'zulu'
        architecture: x64
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Set Release version evn
      run: echo "RELEASE_VERSION=${mvn help:evaluate -Dexpression=project.version -q -DforceStdout}" >> $GITHUB_ENV
    - name: "Build & test"
      run: echo "done!"

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - run: mkdir staging && cp target/*.jar staging


    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
